# global
url: https://discord.steamcmd.net
title: SteamCMD Discord
github: https://github.com/steamcmd/discord

# env specific
api_url: http://localhost:3000/https://discord.com/api/guilds/928592378711912488/widget.json
vue_url: https://vuejs.org/js/vue.js

# build
sass:
  style: compressed

exclude: [".scss", "README.md", "docker-compose.yml", "node_modules", "gruntfile.js", "package.json", "Gemfile", "Gemfile.lock", "LICENSE", "CNAME"]
