# global
url: https://discord.steamcmd.net
title: SteamCMD Discord
github: https://github.com/steamcmd/discord

# env specific
api_url: http://localhost:3000/https://discord.com/api/guilds/928592378711912488/widget.json
vue_url: http://localhost:3000/https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js

# build
sass:
  style: compressed

exclude: [".scss", "README.md", "docker-compose.yml", "node_modules", "gruntfile.js", "package.json", "Gemfile", "Gemfile.lock", "LICENSE", "CNAME"]
